sudo: required
language: node_js
node_js:
  - "6"
services:
  - mongodb
  - docker
after_success:
  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
  - export REPO=quay.io/painejs/pantry-for-good
  - docker login -u $QUAYIO_USERNAME -p $QUAYIO_PASSWORD quay.io
  - docker build -t $REPO .
  - docker tag $REPO $REPO:latest
  - docker tag $REPO $REPO:$TRAVIS_TAG
  - docker push $REPO
env:
  global:
    - secure: L5Hp3TG1/rlsMZQ4y6NOcmc/AaU5goV1Z7XQjm/0BD1KwlnINi6eWPWpCSnv1jXGkRNreJeFkDPLDn42vwedOEEMDkPA0QTVmVRdk+4CImLVjaQm8/isLg7ZJXDMvkEqJqxTngLfZI65zyU6pTIM/bnPm9OT9vn/Mw7Dcd1mYU6487Jwnx8hDcl7O8A6+CicY0trgm4JBukd4dHrjaGdATO3w6YcA4S013ZXURfNCwJgMTUFJcUuaOiSd+oP4dgrff4C1FanCsmTavz0Z8v7dhhJL9hg2XKbnwVykGdMpeZByyLyMVi0JxkNmJnyUIyPsB3F2j29RX/hDkBmk+uJSKGofhWfqAenMjpzUhLaBs93RYhLHqHZkbvHAJ34WC9NNMqnLeLPDiXp6zIjyamJzm/ERbcOkLeVo/OAObCJonXaoymXClXUWlxCqbvJBeR++SH6TDr9YmbGX8NzVgyWyvnA+F50IHvIMnG9xXxOLHgUeqRYZaLilnhEeEyIfHdvHCYXcNsRdWtJNaZjaewVyum5hh4dovKVhohm2Uj2YOKWg+vM8ml2rdVKdlV3Zc3euHvJyLakUrnxq8Fvk0LUwBYZwE761coQDrOIuAi/7nBR0EPeCMTgoChJZMyKVaXJI3IC7QZusfHPvTRoD2XO7ey/GmdTCa429a5XWc5HaP0=
    - secure: JpMfkund7SdJKtOs6tzmfFczELCI9Rg+SOf3AFwl/1qZMzV/eulTtoG+y69PdRmGlUupYi0u6EBOwKFNv7/oSB/ECZAA68wlGfaPQRgpugEGgnY7NzVIjGOSU2euId7nB/v4u/Y8orQ1N2X75aCjB+l7njLQwDWFSEws+EKNrH7WbyJFgiG/dafdRj1qMBGj1tpVOkB7e42Bg/oBEcKUAHH7tVPUErcI4QldSt4lDn0t5uD9gRnFhMHXwpEtCEM3s/RyVSGbILbuSzS5wG2r+H43sE/5ezpza9S1J+k2j0fuR2j27AzqzW72+1xhKpEBOMiM7fQm/lvRJqS0SGU7EZPomFFU/+336x3kzQ/J+9L1Zz7vhsMfBBb43ojO4DzBvKgoe9g3E3gME2axYz2byFxABc2BkSLqsr6JSaNAZRt0xiqbJmFPIMskmtRJIjwgf2KX283zc8qoI4Isv3S9Jr00hZ8yKJeeTrIhSb0s7DTKlo4ZZ8RhceRQVk22KWzbxXEhw7EaRWhQmOtcs4CSrHKFP+PkZFZ43hy9ZxprE6+YuIUuJyEE87uclsTgagzjO3TVWNGxphHjmlbEMF2lxGSrDX4IPfqNadIxzF5SBPBSDXYqHz3Pbtv89cqVDd2a9cHqLAGTSJfyPP4sSgOmvokGrvX/qTjQfTrASw3uGd0=
